# Generated by Django 6.0.4 on 2026-04-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='viajes/'),
        ),
    ]
