# Generated by Django 6.0.4 on 2026-04-20 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajes_app', '0002_viaje_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes_app.viaje')),
            ],
        ),
    ]
