# Generated by Django 6.0.4 on 2026-04-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='descripcion',
        ),
    ]
